/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alok_Agrawal01' at '7/4/17 2:35 PM' with Gradle 2.14
 *
 * @author Alok_Agrawal01, @date 7/4/17 2:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
